---
name: bosh

releases:
- name: bosh
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=256.2
  sha1: ff2f4e16e02f66b31c595196052a809100cfd5a8
- name: bosh-azure-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-azure-cpi-release?v=10
  sha1: 48725899f8b3f0f625bdb3bcff97bc0d6bf193e1

networks:
- name: public
  type: vip

- name: private
  type: manual
  subnets: # You need to update the subnet configuration if you change to another subnet
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns: [168.63.129.16]
    cloud_properties:
      virtual_network_name: boshvnet-crp # Replace with virtual network name
      subnet_name: Bosh # Replace with subnet name for BOSH VM

resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-azure-hyperv-ubuntu-trusty-go_agent?v=3169
    sha1: ff13c47ac7ce121dee6153c1564bd8965edf9f59
  cloud_properties:
    instance_type: Basic_A1

disk_pools:
- name: disks
  disk_size: 25_000

jobs:
- name: bosh
  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: registry, release: bosh}
  - {name: cpi, release: bosh-azure-cpi}

  instances: 1
  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - {name: private, static_ips: [10.0.0.4], default: [dns, gateway]}
#  - {name: public, static_ips: [40.115.248.112]}

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    registry:
      address: 10.0.0.4
      host: 10.0.0.4
      db: *db
      http: {user: admin, password: admin, port: 25777}
      username: admin
      password: admin
      port: 25777

    blobstore:
      address: 10.0.0.4
      port: 25250
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: bosh
      db: *db
      cpi_job: cpi
      enable_snapshots: true
      debug:
        keep_unreachable_vms: false
      max_threads: 10
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm-user, password: hm-password}

    hm:
      director_account: {user: hm-user, password: hm-password}
      resurrector_enabled: true

    azure: &azure
      environment: AzureCloud
      subscription_id: # (TODO Change me!!)
      storage_account_name: # (TODO Change me!!)
      resource_group_name: bosh
      tenant_id: # (TODO Change me!!)
      client_id: # (TODO Change me!!)
      client_secret: # (TODO Change me!!)
      ssh_user: vcap
      ssh_public_key: # (TODO Change me!!) 

      default_security_group: nsg-bosh

    agent: {mbus: "nats://nats:nats-password@10.0.0.4:4222"}

    ntp: &ntp [0.north-america.pool.ntp.org]

cloud_provider:
  template: {name: cpi, release: bosh-azure-cpi}

  ssh_tunnel:
#    host: 40.115.248.112
    host: 10.0.0.4
    port: 22
    user: vcap # The user must be as same as above ssh_user
    private_key: ~/bosh

#  mbus: https://mbus-user:mbus-password@40.115.248.112:6868
  mbus: https://mbus-user:mbus-password@10.0.0.4:6868

  properties:
    azure: *azure
    agent: {mbus: "https://mbus-user:mbus-password@0.0.0.0:6868"}
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: *ntp
