---
jobs:
- name: hello
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: getourneau/alpine-bash-git
      run:
        path: sh
        args:
        - -c
        - |
          echo "Hello World"
